[package]
name = "zerobox-utils-home-dir"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
dirs = { workspace = true }
zerobox-utils-absolute-path = { workspace = true }
